version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: calendar_db_mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'calendar_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'