spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/calendar_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

  batch:
    jdbc:
      initialize-schema: ALWAYS

apartment:
  api:
    path: "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade"
    serviceKey: "eMnMvGML1ccLs2K4gEVX5m8Ld8HkzUBHdgw2Kzo9tt5J8F8rHhikcX6aUWTvn0FXcOCnWdLpqXv8ZVRVd8G1%2Fw%3D%3D"
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    database: h2
