spring:
  profiles:
    active: dev

  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

  datasource:
    url: jdbc:mysql://localhost:3306/calendar_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    web-application-type: none

logging:
  level:
    org:
      springframework:
        jdbc: TRACE
        transaction: DEBUG
        batch: DEBUG